#!/bin/bash

if [ $# -lt 1 ] || [ ! -x "$1" ] ; then
  echo $0 write_glyphs_bin >&2
  exit 1
fi

write_glyphs="$(pwd)/$1"
# shift &

cd "$(dirname "$0")"/resources/fonts/generated

for d in * ; do
  for f in "$d"/*.pnm ; do
    "$write_glyphs" -l 100 "$f" ~/ocr/latin_letters "$d" || return $?
  done
done

cd ..

for d in cyrillic_tahoma_8_bold noname russian segoeUI_11 segoeUI_8_bold tahoma_8_bold trebuchetMS_10_bold ; do
  for f in "$d/"*.pbm ; do 
    "$write_glyphs" -l 100 "$f" "${f:0:-3}txt" "$d" || return $?
  done 
done 
